### ISSUE TITLE
Proposition de traduction : Gatsby pour les applications Web

### ISSUE THREAD

**Issue by phacks** [jamstatic/jamstatic-fr#122]
Proposition de traduction : “[Gatsby for Apps](https://www.gatsbyjs.org/blog/2018-11-07-gatsby-for-apps/)”, publié par Dustin Schau (dev chez Gatsby) en novembre dernier sur le blog de Gatsby.

Le post explique comment Gatsby peut aller plus loin que les sites “purement” statiques et permet de créer des “applis Web”, en prenant pour exemple un clone de Gmail recodé en Gatsby.

Je trouve l'article très intéressant, et c'est une problématique qui m'intéresse beaucoup. En effet, ça permet de faire un pont entre deux domaines qui ont jusqu'ici été assez cloisonnés (enfin de ce que j'en sait).

Qu'en pensez-vous ?

**Comment by DirtyF** [comment]
👋 @phacks ça a l'air cool oui, fais toi plaisir. Surtout qu['on a pas publié d'article trop technique sur Gatsby jusqu'à présent](https://jamstatic.fr/categories/gatsby/). 

Le développement SSR/Static n'a jamais été aussi fusionnel et les projets les plus populaires actuellement sont ceux comme Next et Nuxt qui propose le meilleur des deux mondes. Je comprends que les développeurs aient envie d'utiliser des outils polyvalents basés sur des frameworks.

J'avais repéré quelques articles intéressants publiés sur le blog de Gatsby, dont celui plus meta sur le _content mesh_, mais qui sont aussi utiles pour attirer l'attention de profils moins techniques.
