### ISSUE TITLE
Traduire l'article "Implementing a CMS in 3 Days"

### ISSUE THREAD

**Issue by DirtyF** [jamstatic/jamstatic-fr#136]
source: https://www.dwolla.com/updates/implementing-netlify-cms/

**Comment by Narno** [comment]
Pour suivi, la PR est accessible ici : #137.

**Comment by Narno** [comment]
Plusieurs traductions envisagées pour "Implementing a CMS in 3 Days" :
1. "Implémenter un CMS en 3 jours"
2. "Mettre en place un CMS en 3 jours
3. "Intégrer un CMS en 3 jours"

Je pense que finalement, "intégrer" est le terme le plus adéquate. @DirtyF as-tu un avis ? :-) Merci.

**Comment by DirtyF** [comment]
Je suis d'accord, la 3 semble plus adaptée dans ce contexte.

**Comment by DirtyF** [comment]
(je te propose qu'on échange sur la traduction dans les commentaires de la PR plutôt)

**Comment by Narno** [comment]
Done!

https://jamstatic.fr/2019/06/22/cms-headless-en-3-jours/

Un grand merci à @DirtyF pour ses précieux conseils sur la manière de s'organiser pour traduire, relire, ajuster ! 😘
