### ISSUE TITLE
Comparatif des offres d'hébergements

### ISSUE THREAD

**Issue by DirtyF** [jamstatic/jamstatic-fr#14]
Afin de pouvoir un peu mieux s'y retrouver dans toutes les offres existantes: 
## Fonctionnalités
- [ ] Synchronisation avec GitHub/GitLab/autre
- [ ] CMS
- [ ] Optimisation des assets
- [ ] Déploiemnt sur CDN
- [ ] Support de HTTPS
- [ ] Support de HTTP2
- [ ] Webhooks
## Prestataires
- GitHub
- GitLab
- Netlify
- CloudCannon
- Surge.sh
- BowTie
- Amazon S3
- Heroku

https://www.thenewdynamic.org/tools/hosting-deployment/

**Mise à jour** : J'ai crée un Google Docs public à compléter : https://docs.google.com/spreadsheets/d/1FuiC29pnWsRemqvQh3UcHAZSkz_3p-pq-5-6m5ZHdzU/edit#gid=0

/cc @borisschapira

**Comment by DirtyF** [comment]
n'hésitez pas à compléter la liste des choses à comparer. Si certains ont des expériences avec certains services, ça serait sympa de partager et de mutualiser les retours ❤️

**Comment by bertrandkeller** [comment]
Il y a des ressources concernant l‘hébergement avec Dropbox, non ?
https://github.com/tombh/jekbox

Après je ne sais si ça rentre dans le cadre de la comparasion de services…
