### ISSUE TITLE
Offrir une API REST avec Jekyll

### ISSUE THREAD

**Issue by borisschapira** [jamstatic/jamstatic-fr#15]

**Comment by DirtyF** [comment]
Liens relatifs :
 
- http://blog.pixelastic.com/2015/01/15/this-blog-now-has-an-api/
- https://github.com/riichard/jekyll-rest-api
- https://github.com/benbalter/jekyll-restful-api-generator

**Comment by DirtyF** [comment]
https://github.com/18F/jekyll_pages_api
