### ISSUE TITLE
Un article sur l'état des MarketPlace de thèmes Jekyll ?

### ISSUE THREAD

**Issue by borisschapira** [jamstatic/jamstatic-fr#16]

**Comment by DirtyF** [comment]
Liens relatifs : 

-  https://jekyllthemes.io/
-  http://jekyllthemes.org/
-  http://themes.jekyllrc.org/
-  https://themeforest.net/category/static-site-generators/jekyll

**Comment by borisschapira** [comment]
Attention à bien mentionner ceux qui offrent des thèmes packagés en gems et ceux qui ne le font pas. Je pronostique la mort des seconds aussi vite que le système gagnera en momentum.

**Comment by DirtyF** [comment]
À l'heure où j'écris ces lignes, les themes packagés en gem se comptent sur les doigts de la main car ils ne gèrent pas encore les assets, mais c'est prévu pour la version 3.3.

**Comment by DirtyF** [comment]
GitHub est en train de travailler sur des themes, ce qui laisse présager que GitHub Pages proposera quelques themes par défaut:

- https://github.com/broccolini/swiss
- http://broccolini.net/athena/
