### ISSUE TITLE
Un Use Case sur un site e-commerce

### ISSUE THREAD

**Issue by borisschapira** [jamstatic/jamstatic-fr#17]

**Comment by DirtyF** [comment]
Liens relatifs : 

- https://snipcart.com/blog/static-site-e-commerce-part-2-integrating-snipcart-with-jekyll
- https://github.com/snipcart/snipcart-jekyll-integration

**Comment by bertrandkeller** [comment]
Solution JS : 
http://simplecartjs.org/
http://minicartjs.com/

Static : 
https://builtwithbison.com/ (Statamic)

Snipcart : 
http://cloudcannon.com/tutorials/2014/07/30/e-commerce-now-on-cloud-cannon-with-snipcart.html
https://snipcart.com/blog/static-site-e-commerce-integrating-snipcart-with-middleman
https://www.netlify.com/blog/2015/08/25/a-great-fast-static-e-commerce-experience-with-6-easy-tools/

Plugin Jekyll
https://github.com/jekyll-store/front

Pay with a tweet : 
http://www.paywithatweet.com/

**Comment by DirtyF** [comment]
https://jamstatic.fr/2017/08/28/un-site-ecommerce-statique-avec-hugo/
