### ISSUE TITLE
Les cas d'usages évidents pour un site statique

### ISSUE THREAD

**Issue by borisschapira** [jamstatic/jamstatic-fr#18]
- [ ] Site perso, serverless pour s'éviter de la maintenance, des mises à jour, vulnérabiltés et hébergement gratuit
- [ ] Site de contenus avec peu d'interactions utilisateurs (landing, page, société, etc.)
- [ ] SPA full et APIs tierces

**Comment by tut-tuuut** [comment]
Site perso pour lequel on ne veut pas se prendre la tête en maintenance/mise à jour/vulnérabilités.
