### ISSUE TITLE
Some images not found (404)

### ISSUE THREAD

**Issue by yaaax** [jamstatic/jamstatic-fr#247]
See page [Créer des mises en page dynamiques avec Jekyll](https://jamstatic.fr/2017/02/10/creer-des-mises-en-page-dynamiques-avec-jekyll/)

After "_ci-dessous une sélection d’études de cas_", 4 images are not displayed.

In the console, 5 errors (404) :
- `canon-unleashprint-full.jpg`
- `canon-unleashprint-fullpage.jpg`
- `dogs-trust-fullpage.jpg`
- `lynx-fullpage.jpg`
- `lynx-calm-fullpage.jpg`

**Comment by DirtyF** [comment]
Merci c'est corrigé 🙏
