### ISSUE TITLE
Refactoriser le CSS avec Tailwind

### ISSUE THREAD

**Issue by DirtyF** [jamstatic/jamstatic-fr#250]
Parce que ce n'est pas mon métier, parce que je ne veux pas à avoir à maintenir un inventaire de code CSS custom pour une mise en page aussi simple, parce que je souhaite faire l'expérience de l'approche utility-first, une refactorisation du CSS du site avec Tailwind semble quelque chose d'attirant.

- [x] Installation / Configuration
  - [x] Installer Tailwind 2.0 avec Hugo
  - [x] Personnaliser la configuration pour utiliser les fonts Poppins et Roboto
  - [x] Personnaliser la configuration des couleurs du site
- [x] Composants
  - [x] Header
  - [x] Navigation
  - [x] Footer
  - [x] Items liste (accueil)
- [ ] Articles
  - [x] Métadonnées d'un article
  - [x] Typographie : titres, corps de texte
  - [x] Étendre les styles du plugin `typography` pour les couleurs et police des titres
  - [x] Citations
  - [x] Figure
  - [x] Embeds
  - [ ] Syntax Highlighting / Chroma
  - [x] Inserts (info, mise à jour, astuce)
- [x] Single page (ex : à propos)
- [x] Page Catégorie
- [ ] Résultats de recherche
- [x] Supprimer le code mort
- [x] Responsive
- [x] Dark Mode
- [x] Purge CSS
- [ ] Critical CSS ?
- [ ] Cumulative Layout Shift ?
- [ ] Comparer le poids du CSS avant/après

**Comment by DirtyF** [comment]
WIP: https://www.loom.com/share/501eb3989517476185c6894ff6568fd7

- Comment overrider les styles du plugin typography pour les niveaux de titres et les couleurs de liens ?

**Comment by Narno** [comment]
> WIP: [loom.com/share/501eb3989517476185c6894ff6568fd7](https://www.loom.com/share/501eb3989517476185c6894ff6568fd7)

Wahou, t'as vachement bien, avancé ! 👏

**Comment by Narno** [comment]
> Comment overrider les styles du plugin typography pour les niveaux de titres et les couleurs de liens ?

Je pense que le plus simple c'est d'utilsier les directives @layer et @apply dans la CSS source : https://tailwindcss.com/docs/adding-base-styles#using-css.

Par exemple :
```css
@layer base {
  h1 {
    @apply text-2xl;
  }
  h2 {
    @apply text-xl;
  }
  a:hover {
     @apply underline;
  }
}
```

**Comment by DirtyF** [comment]
Oui, ça va vite, le plus long c'est configurer Hugo et Tailwind, pas écrire le CSS, un comble.

Avec le plugin `typography` et il est maintenant possible d'étendre les propriétés
https://github.com/tailwindlabs/tailwindcss-typography/releases/tag/v0.3.0

Je pousserais quand je serais satisfait d'une version qui à minima est pas pire que ce qu'on a en ligne.

**Comment by DirtyF** [comment]
Couleurs à revoir pour le dark mode: https://www.loom.com/share/7eea718b5f344aa486b1d2d1a669e140

**Comment by Narno** [comment]
> Couleurs à revoir pour le dark mode: [loom.com/share/7eea718b5f344aa486b1d2d1a669e140](https://www.loom.com/share/7eea718b5f344aa486b1d2d1a669e140)

Comme basculer la couleur des titres en #7DACFF pour d'avantage de contraste avec le fond ?

**Comment by DirtyF** [comment]
Oui, je me suis pas encore penché sur l'extension des couleurs personnalisées, pour le moment j'utilise le violet de Tailwind.
