### ISSUE TITLE
Rendre le site web jamstatic.fr offline first

### ISSUE THREAD

**Issue by antoinentl** [jamstatic/jamstatic-fr#29]
Liste des choses à faire :

- décider ce qui est stocké localement, sur le *device* de l'utilisateur. Proposition : tout, tant que le site ne dépasse pas 5Mo ;
- générer automatiquement un fichier JavaScript avec Service Workers. [Quelques ressources](https://pinboard.in/u:maxbarners/t:jekyll/t:serviceworker/) ;
- en option, et dans le cas où la quantité de données serait trop importante, proposer un bouton "Lire le site/l'article hors ligne", voir [Implementing "Save For Offline" with Service Workers](https://una.im/save-offline/).

**Comment by DirtyF** [comment]
@antoinentl Entièrement d'accord sur le principe, j'hésite sur la solution à employer (le plugin jekyll-offline n'est pas encore au point et on trouve plein de solutions différentes).

Une implémentation possible mais complexe est [celle de Jeff Posnick de chez Google](https://github.com/jeffposnick/jeffposnick.github.io/tree/work/src), auteur de sw-precache.

https://jeffy.info/2017/01/24/offline-first-for-your-templated-site-part-2.html

@nhoizey est en train d'implémenter le offline sur son site, j'ai vu que toi aussi tu avais un service worker en place, à terme j'aimerais pourvoir itérer sur les versions de cache facilement, mais on peut commencer au plus simple.

Toute aide est la bienvenue, je ne me suis pas encore penché trop en détail sur le sujet.

**Comment by antoinentl** [comment]
L'idée, peut-être très naïve de ma part, serait d'automatiser facilement la mise à jour du Service Worker utilisé, en partant du principe que nous sommes dans [le cas 1 présenté par Jeff Posnick](https://jeffy.info/2017/01/24/offline-first-for-your-templated-site-part-2.html). Ce qui veut dire plusieurs choses :

- établir automatiquement la liste des fichiers du site à stocker localement : HTML, CSS, XML (pour le flux Atom), les fontes (si on décide de les rapatrier de Google, ce qui ne serait pas une mauvaise chose), et les images (dont celles des articles si on les rapatrie également) ;
- modifier la liste des fichiers à mettre en cache en fonction des mises à jour ;
- modifier la version du Service Worker en fonction des mises à jour (ce qui permet, si j'ai tout compris, au device de savoir ce qu'il faut qu'il aille chercher comme nouveaux contenus/fichiers).

Ça vous paraît trop simpliste @DirtyF et @nhoizey ?

**Comment by DirtyF** [comment]
@antoinentl Partons simple. On a même pas une douzaine d'articles, ça justifie pas encore de développer un service worker inutilement complexe. On verra à l'usage.

On peut générer la liste des URLs des posts avec `site.posts`, celle des fichiers static avec [`site.static_files`](https://jekyllrb.com/docs/static-files/)

Même chose pour la mise à jour de la version du cache du Service Worker, on peut commencer par générer une version à la main au début et itérer ensuite.

N'hésite pas à ouvrir une PR très tôt même avec peu de code, on pourra te faire des retours au plus tôt comme ça ;)

**Comment by nhoizey** [comment]
Je suis d'accord sur le principe général.

Il faut à mon avis :
- mettre en cache dès le départ la page d'accueil et le dernier billet, avec leurs ressources (CSS, JS, images) et c'est tout
- mettre en cache les autres contenus au fur et à mesure qu'ils sont consultés

Pour la version, manuel, comme dit @DirtyF, c'est très bien.

Par contre, ça ne permet pas « au device de savoir ce qu'il faut qu'il aille chercher comme nouveaux contenus/fichiers », tout ça reste à faire dans le code soi-même.

**Comment by DirtyF** [comment]
Un exemple ultra basic qui marche chez Netlify (notre hébergeur): 

https://github.com/oliverdunk/TodoPWA/blob/master/sw.js

**Comment by nhoizey** [comment]
"We'll assume the application is never updated" ;-)

**Comment by bertrandkeller** [comment]
**Implementing "Save For Offline" with Service Workers**
http://una.im/save-offline/

Un bouton sur chaque article pour les sauvegarder à la main ?
