### ISSUE TITLE
Ajouter une partie veille à partir des "likes" du compte Twitter

### ISSUE THREAD

**Issue by antoinentl** [jamstatic/jamstatic-fr#30]
Ajouter une partie veille (ou un autre terme plus alléchant) sur le site jamstatic.fr, à partir du [flux des likes du compte Twitter](https://twitter.com/jamstatic_fr/likes).

Questions :

- est-ce qu'il faut automatiser cela ?
- est-ce qu'il faut créer un *post* pour chaque ressource/lien/like ?
- est-ce qu'il faut tagger ou catégoriser les différents liens proposés ?

**Comment by DirtyF** [comment]
Yep, ça aussi ça fait un moment que j'y pense 💭 

Pour info il existe un channel _bookmarks_ sur le Slack avec pas mal de ressources. Les _likes_ de Twitter contiennent parfois simplement… des _likes_ qui n'ont pas vocation à figurer dans une partie veille.

Il existe aussi un[ flux RSS associé généré via une app déployée sur Heroku](https://feedly.com/i/subscription/feed/http://jamstatic-bookmarks.herokuapp.com/feed/bookmarks) mais qui ne liste pas la totalité des liens postés dans #bookmarks.

@jbleuzen avait proposé de poster un post dans une collection via un bot (https://github.com/jamstatic/BookmarkCommiterBot), j'aimais bien l'idée!

Si je n'ai pas crée la collection et ajouté une partie veille ou liens sur le site, c'est parce que je trouve fastidieux de devoir créer cela à la main 😓  mais on pourrait faire l'inverse : 

- une tâche `rake` qui crée un nouveau post dans une collection `_links`
- une tâche `rake` qui commit le nouveau lien sur le site
- un flux RSS pour la collection en se basant sur le modele de jekyll-feed (qui ne marche que pour des posts et pas des collections)
- import du RSS dans le channel #bookmarks de Slack.
