### ISSUE TITLE
Update headers for HSTS

### ISSUE THREAD

**Issue by DirtyF** [jamstatic/jamstatic-fr#62]
```
Error: No includeSubDomains directiveThe header must contain the `includeSubDomains` directive.
Error: No preload directiveThe header must contain the `preload` directive.
```

https://hstspreload.org/?domain=jamstatic.fr should be valid

**Comment by DirtyF** [comment]
https://hstspreload.org/?domain=jamstatic.fr  is now valid with https://github.com/jamstatic/jamstatic-fr/commit/c352f442554f4592308746b969bc199b61e8dc6e

> jamstatic.fr is now pending inclusion in the HSTS preload list!

Please make sure that jamstatic.fr continues to satisfy all preload requirement, or it will be removed. Please revisit this site over the next few weeks to check on the status of your domain.

**Comment by bertrandkeller** [comment]
C'est quand même assez fou ce passage par le test pour comprendre certaines choses.
Je n'avais pas idée de l'existence de cette configuration pour avoir le HSTS.
