### ISSUE TITLE
Les formats d'export personnalisés dans Hugo

### ISSUE THREAD

**Issue by DirtyF** [jamstatic/jamstatic-fr#63]

**Comment by antoinentl** [comment]
Je vais faire des recherches pour connaître les possibilités d'export en EPUB, donc je m'y colle !

**Comment by DirtyF** [comment]
@antoinentl vois avec @jonathanulco qui a aussi de son côté un retour d'expérience à faire sur d'autres formats et qui avait commencé à rédiger quelque chose

**Comment by antoinentl** [comment]
Je ravive un peu ce projet de billet, @jonathanulco est-ce que tu aurais des exemples de formats personnalisés à partir d'Hugo ? Pour le moment je ne trouve rien de probant pour l'export au format EPUB.

**Comment by jonathanulco** [comment]
Getty a l'air d'avoir un bout de js pour ça https://github.com/gettypubs/artistryinbronze/blob/dd87abd9bc0f867ea9354b6848237c49c54b1d27/public/assets/js/build-epub.js
mais on a aussi https://github.com/gettypubs/artistryinbronze/blob/dd87abd9bc0f867ea9354b6848237c49c54b1d27/content/epub.md

**Comment by antoinentl** [comment]
Merci 😃 c'est ce que j'étais en train de regarder ! Je n'ai pas l'impression que des output formats complexes comme le PDF ou l'EPUB soient prévus *nativement* dans Hugo.

Ceci dit la méthode de Getty est relativement simple, je vais tester dans les prochaines semaines !

**Comment by jonathanulco** [comment]
C'est sûr que pour exporter du json c'est plus trivial :p https://www.raymondcamden.com/2017/05/18/creating-a-json-feed-for-hugo

**Comment by DirtyF** [comment]
@antoinentl Ce n'est pas natif mais Hugo te permet d'ajouter tes propres formats.

[Getty utilise plusieurs outils complémentaires pour générer des epubs 3.x valides](https://github.com/gettypubs/artistryinbronze/blob/master/EPUB-README.md#epub-generation)

**Comment by bertrandkeller** [comment]
Super intéressant cette conversation, je me suis posé le même genre de question et j'ai vu que c'était pas si facile.

**Comment by DirtyF** [comment]
@antoinentl je pensais que Quire permettait déjà l'export au format ebook mais [ça n'a pas l'air d'être encore le cas](https://github.com/egardner/quire-demo/blob/ab6cb5d7fcd29c2306e4cfaad164826acd6d8072/data/publication.yml#L17).
