### ISSUE TITLE
Rédiger, éditer et publier des contenus en Markdown

### ISSUE THREAD

**Issue by Narno** [jamstatic/jamstatic-fr#68]
1. Présenter les avantages du format pour la rédaction et les usages
2. Montrer l'omniprésence du Markdown dans différents contextes
3. Makrdown dans le contexte des workflows de publication modernes

# Rédiger en Markdown 

## Clients lourds:

- [ ] [Typora](https://typora.io/)
- [ ] [MacDown](https://macdown.uranusjr.com/)
- [ ] [iA Writer](https://ia.net/writer/)
- [ ] [Caret](https://caret.io/)
- [ ] [Mou](http://25.io/mou/)
- [ ] [Atom](https://atom.io/) + [Markdown Writer](https://atom.io/packages/markdown-writer) + [Markdown Preview](https://atom.io/packages/markdown-preview) 

## Services en ligne

- GitHub, GitLab, BitBucket (documentation logicielle)
- Wordpress.com (JetPack) (blog)
- [StackEdit](https://stackedit.io/)
- [Dillinger](https://dillinger.io/)
- [Papers](https://paper.dropbox.com/) (Dropbox) (Notes de Réunion) 
- GitBook

## Headless CMS

- Forestry.io
- NetlifyCMS 
- [Contentful](https://www.contentful.com/blog/2015/09/22/markdown/)

**Comment by DirtyF** [comment]
[VS Code](https://code.visualstudio.com/Docs/languages/markdown), [Sublime Text](https://github.com/SublimeText-Markdown/MarkdownEditing) et [Vim](https://github.com/plasticboy/vim-markdown) supportent tous le Markdown. 

Mais peut-être souhaites-tu présenter des éditeurs plus grand public ?

**Comment by Narno** [comment]
En effet, je pensais orienter le message en direction des "non techniques" et donc parler des éditeurs clef en main, très accessible.

**Comment by DirtyF** [comment]
OK donc je sais même pas si Atom rentre dans cette catégorie, y'a toujours un peu de configuration (donc pas clef en main)

**Comment by DirtyF** [comment]
Pour macOS :

- https://ulyssesapp.com/
- https://bywordapp.com/
- https://desk.pm/ 

Pour Windows : 

- http://writemonkey.com
- http://markdownpad.com/

**Comment by antoinentl** [comment]
Alors en éditeur "grand public" il y a par exemple :

- [Typora](https://typora.io/) : Mac OS, Windows, Linux ;
- [iA Writer](https://ia.net/writer/) : Mac OS, iOS, Android ;
- [Remarkable](https://remarkableapp.github.io/) : Windows, Linux ;
- [Haroopad](http://pad.haroopress.com/user.html) : Mac OS, Windows, Linux ;
- [UberWriter](http://uberwriter.wolfvollprecht.de/) : Ubuntu (Linux) ;
- etc.

**Comment by Narno** [comment]
Question : doit-on restreinte la liste à ceux qui supporte la notion de front matter ? Pour ma part c'est oui ! :-)

**Comment by DirtyF** [comment]
@Narno Oui, pour une utilisation spécifique pour des générateurs qui embarquent des méta-données, c'est un excellent critère de sélection.

**Comment by antoinentl** [comment]
@Narno "front matter" ça concerne les données d'en-tête du type titre ou date ?

**Comment by Narno** [comment]
@antoinentl toutafé :-)

ref.: https://jekyllrb.com/docs/frontmatter/

**Comment by jygastaud** [comment]
Une note importante, pour les éditeurs supportant le front matter, sera de dire quel format (yaml, json, toml) sont supportés.

**Comment by DirtyF** [comment]
Pour IA Writer, ils se basent sur Multi Markdown qui ne supporte qu'une partie de YAML apparemment : https://fletcher.github.io/MultiMarkdown-5/metadata.html

**Comment by Narno** [comment]
@jygastaud @DirtyF je pense que la plupart des éditeurs ne supportent *que* YAML non ?

**Comment by jygastaud** [comment]
De mon côté je ne saurai pas dire je n'en utilise pas.
Mais cela peut être un critère de choix tant pour le développeur (s'il a le choix comme avec Hugo par exemple), soit pour le contributeur.

**Comment by DirtyF** [comment]
- MacDown supporte le frontmatter de Jekyll, soit le YAML. (source: https://macdown.uranusjr.com/features/)
- StackEdit supporte seulement YAML

**Comment by Narno** [comment]
Oh hey, doucement le bot : 2 mois c'est pas la mort non plus hein. Prout prout.

**Comment by DirtyF** [comment]
- https://www.sitepoint.com/the-best-markdown-editors-for-mac/
- https://www.sitepoint.com/the-best-markdown-editor-for-linux/
- https://www.sitepoint.com/best-markdown-editors-windows/

Typora et Haroopad receuille le plus de votes sur:
https://www.slant.co/topics/1852/~markdown-editors-for-windows

**Comment by Narno** [comment]
Oui, Typora est également mon chouchou, que ce soit sur Mac ou sur Windows.

**Comment by Narno** [comment]
Une alternative open-source à Typora : https://github.com/marktext/marktext

**Comment by DirtyF** [comment]
Ils sont à fond sur Mardown en Chine on dirait

**Comment by DirtyF** [comment]
Note: Pour le grand public, il y a des chances qu'ils éditent du Markdown davantage dans l'interface web d'un headless CMS.

Les éditeurs de Markdown me semblent destinés aux personnes qui écrivent beaucoup, si le workflow de publication implique d'utiliser Git, alors un IDE intégré semble plus approprié, GitBook étant uniquemenent destiné à des formats de livres si je ne m'abuse. 

C'est pour cette raison que j'ai tendance privilégie un IDE comme Atom/VSCode, il me permet de linter mon markdown avec remark, de bénéficier de la correction syntaxique et grammaticale et d'interagir facilement avec des dépôts de contenu distants, et bien d'autres choses encore.

**Comment by DirtyF** [comment]
Je ne sais pas quel est le périmètre que s'était fixé @Narno pour cet article si son but mais se focaliser sur le format léger et les éditeurs sans aborder la question du workflow d'écriture et de publication me semble une fausse promesse si on vise les contributeurs — qui choisissent rarement les outils. 

Si c'est pour inciter les gens à s'intéresser à Markdown et le tester alors oui mentionner des éditeurs fait sens.

**Comment by antoinentl** [comment]
:pray: Je suis bien d'accord sur la nécessité de parler des workflows ! Et finalement l'enjeu des langages de balisage léger est bien celui-ci, il faut toujours associer une chaîne de publication à un langage, par exemple :

- Markdown + Pandoc
- AsciiDoc + Asciidoctor
- etc.

**Comment by Narno** [comment]
Hello @DirtyF,

Tout à fait : je ne sais pas trop où j'allais avec cette idée de post (la preuve il ne s'est pas passé grand chose depuis des mois...).

Je pense que mon idée était de rédiger une aide au choix en fonction de ses besoins et de ses habitudes, à destination des utilisateurs qui ne connaissent pas bien Markdown ou qui hésitent à sauter le pas.

En effet, il y a certainement 2 approches :
1. utiliser Markdown comme langage de balisage simple, pour prendre des notes, écrire un article, etc.
2. utiliser Markdown dans un objectif de publication, et donc dans le contexte d'un workflow

Je pense que mon idée de fond était surtout de démystifier le Markdown : ce n'est pas un langage de "code" mais bien un langage de balisage, standard, simple.

**Comment by DirtyF** [comment]
@Narno J'aime bien l'idée des deux parties, commencer du début, pour finir sur les portes que ça ouvre dans l'écosystème.

**Comment by Narno** [comment]
https://paper.dropbox.com/doc/Rediger-en-Markdown--AgPx4MhfS~L6h20OkpgSgFVBAQ-TnHdtgZurnfrE538GHecI
