### ISSUE TITLE
Entretien avec les créateurs d'Antora

### ISSUE THREAD

**Issue by antoinentl** [jamstatic/jamstatic-fr#90]
Voici une proposition de billet : un entretien avec les créateurs d'[Antora](https://antora.org/), "A static site generator for making documentation sites from one or more versioned content repositories", un projet basé sur AsciiDoc et Asciidoctor qui est en train d'arriver !

Je me charge de contacter les créateurs, de préparer les questions, j'aurais probablement besoin d'un coup de main pour valider les questions en anglais (coucou @DirtyF), et ensuite pour relire mes traductions de l'anglais au français.

(Bonus : une publication sur The New Dynamic pour la version anglaise).

**Comment by DirtyF** [comment]
Go go go

**Comment by antoinentl** [comment]
Prise de contact en cours !

**Comment by antoinentl** [comment]
Je suis encore dessus (non je ne veux pas lâcher).
