### ISSUE TITLE
Automatiser les optimisations pour Jekyll et Hugo

### ISSUE THREAD

**Issue by YoavRheims** [jamstatic/jamstatic-fr#98]
Ceci est une suggestion pour un billet sur le blog :

1. Génération du Critical CSS
2. Enlever le CSS non utilisé
3. Optimisation des images (webp, responsiveness, svg map)
4. Optimisation du browser cache pour les fichiers statiques
5. Minification du CSS, JS et HTML

**Comment by DirtyF** [comment]
@YoavRheims Est-ce que c'est un billet que tu souhaites écrire ?

**Comment by DirtyF** [comment]
Le 1 et le 2 ne sont pas des choses prises en compte en natif par les générateurs. Il faudra donc se reposer sur son workflow maison et/ou utiliser les outils de l'écosystème de `npm` comme on le ferait susr l'importe quel projet. Ça demande de jongler avec deux stacks.

Même chose pour le 3, ces problèmatiques front-end sont à gérer soit avec son workflow usuel,  soit en ayant recours à un service comme Cloudinary ([voir l’article de @nhoizey pour Jekyll](https://jamstatic.fr/2016/08/31/gestion-images-responsive-avec-jekyll-cloudinary/)) ou Imgix par exemple.  

Pour le 4, c'est quelque chose qui peut-être délégué chez certains hébergeurs comme Netlify qui invalidera automatiquement le cache à chaque push sur le repo et donc le déploiement sur leurs CDN.

[Hugo est en train d'ajouter des fonctionnalités à ce niveau (bundle, minify, etc.)](https://github.com/gohugoio/hugo/issues/4446)

Il existe des plugins Jekyll pour le point 5 mais là encore le plus simple est d'utiliser les options proposées par Netlify:

![netlify assets optimization](https://user-images.githubusercontent.com/103008/36682558-b0bd7542-1b1b-11e8-88c0-0f5c3eebc47f.png)

J'invite les autres JAMstackers à nous faire part de leur retour d'expérience si ça peut aider à écrire un article sur la gestion des assets et du critical path avec différents générateurs.

**Comment by YoavRheims** [comment]
En effet, Netlify est encore la meilleure solution. Il manque juste le Critical CSS.
